function data = importfile3(workbookFile, sheetName, dataLines, column)
%IMPORTFILE3 Import data from a spreadsheet
%  data = IMPORTFILE3(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the numeric data.
%
%  data = IMPORTFILE3(FILE, SHEET) reads from the specified
%  worksheet.
%
%  data = IMPORTFILE3(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  data = importfile3("C:\Users\zsult\Box Sync\Banks Lab (zsultan@wisc.edu)\Slice\DOI, Ketamine, Saline - 24hr\210603 - ch4 TBS40 analysis.xlsx", "Sheet1", [29, 119]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Jun-2021 23:59:39

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [29, 119];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = column + dataLines(1, 1) + ":" + column  + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = "VarName12";
opts.VariableTypes = "double";

% Import the data
data = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = column + dataLines(idx, 1) + ":" + column + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    data = [data; tb]; %#ok<AGROW>
end

%% Convert to output type
data = table2array(data);
end