function dataToPlot = importATFtraces(filename, dataLines)
%importATFtraces Import example from an abf text file
%  dataToPlot = importATFtraces(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the numeric data.
%
%  dataToPlot = importATFtraces(FILE, DATALINES) reads data for
%  the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  dataToPlot = importATFtraces("C:\Users\zsult\Box Sync\Banks Lab (zsultan@wisc.edu)\Slice\Example Traces\DOI - 210528006, 210528010 ch3.atf", [4, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 07-Oct-2021 14:43:15

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [4, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Timems", "Trace15", "Trace178"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
dataToPlot = readtable(filename, opts);

%% Convert to output type
dataToPlot = table2array(dataToPlot);
end