function [drugOut] = popupGetDrugSelection()
S.Preselects = getDrugList;
S.fh = figure('units','pixels',...
    'position',[500 500 300 150],...
    'menubar','none',...
    'numbertitle','off',...
    'name','Audit experiment parameters',...
    'resize','off');
S.pp = uicontrol('style','pop',...
    'unit','pix',...
    'position',[20 50 120 30],...
    'string',S.Preselects,...
    'value',1);
S.b = uicontrol('style','pushbutton',...
    'unit','pix',...
    'position',[160 50 80 30],...
    'string','Select',...
    'callback',{@pb_call,S});
movegui('center');
uiwait;
S = guidata(S.fh);
drugOut = S.drugOut;
close(S.fh);
end

function [S] = pb_call(hObject, ~, S)
% [S] = varargin{3};
% Callback for pushbutton.
S.drugOut = S.Preselects{get(S.pp,'Value')};
disp(S.drugOut);
guidata(hObject,S);
uiresume;
end

